--- # Database configuration

- hosts: server
  user: ubuntu
  become: yes
  connection: ssh


  tasks:
    - name: apt update
      apt:
        update_cache: true
        cache_valid_time: 3600
        force_apt_get: true


    - name: install qemu-guest-agent and https
      apt:
        name:
          - qemu-guest-agent
            #- https
          - nginx
          - software-properties-common
          - git
        state: latest
        #notify: service start
    - name: update
      apt:
        update_cache: yes



  #handlers:

    - name: service start
      service:
        name: qemu-guest-agent
        state: started

    - name: Installation install software-properties-common
      apt: name=software-properties-common state=present

    - name: add repositories
      become: true
      apt_repository:
              #validate_certs: no
        repo: 'ppa:ondrej/php'
        #   state: present
        #apt_repository:
              #repo="ppa:ondrej/php"

    - name: update system
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: add ppa
      apt_repository:
        validate_certs: no
        repo: 'ppa:ondrej/php'
        state: present

    - name: update
      apt:
        update_cache: yes
        cache_valid_time: 3600


    - name: "Updating the repo"
      apt: update_cache=yes

    - name: Installation PHP 8.0
      apt: name=php8.0 state=present

    - name: install php
      apt:
        name:
                #- php8.0 
          - php8.0-fpm
          - php8.0-mysql
          - php8.0-curl
          - php8.0-cli
          - php8.0-gd
          - php8.0-zip
        state: latest

    - name: service start
      service:
        name: apache2
        state: stopped

    - name: remove apache2
      apt:
        name: apache2
        state: absent
        autoremove: yes

    


    - name: service start
      service:
        name: nginx
        state: started
        enabled: true


    - name: enable service php-fpm
      service:
        name: php8.0-fpm
        state: started
        enabled: true
